dataset:
  root: /pool1/home/ysxin/E3nnVB/VB
  task: regression

training:
  seed: 0
  device: cuda
  num_workers: 1
  batch_size: 64
  epochs: 2000
  lr: 1e-4
  weight_decay: 1e-5
  loss: mse
  # 学习率调控器
  scheduler: 
    name: cosine
    min_lr: 1e-6

model:
  lap_pe_k : 8
  signnet:
    phi_hidden: 64
    phi_out: 16
    phi_layers: 2
    rho_hidden: 128
    out_dim: 32
    rho_layers: 2

  output_activation: sigmoid
  
  # --- irreps --- 
  irreps_in: "35x0e" # 3 + out_dim(32) = 35
  hidden_irreps: "48x0e + 24x1o"
  irreps_out: "1x0e"
  edge_mlp_hidden: 64

  # ---geometry---
  lmax_attr: 1 # 一阶球谐函数
  edge_scalar_dim: 34
  use_r2: true
  use_rbf: true
  rbf:
    r_min: 0.0
    r_max: 6.0
    num_basis: 32
    sigma: 0.1

  # ---network---
  layers: 4
  norm: "batch"
  pool: "mean"