"""Build model-ready graph fields from parsed ``.xmo`` molecule facts."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from data.lap_pe import lapPeFromEdges
from data.schema import ProcessedMolecule, ProcessedStructureSample
from data.xmo_parser import ParsedXMOMolecule


@dataclass
class BuiltMoleculeSample:
    """Structured molecule-level sample produced from one parsed ``.xmo`` file."""

    molecule_id: str
    atom_symbols: list[str]
    atom_numbers: np.ndarray
    atom_positions: np.ndarray
    structures: list[ProcessedStructureSample]


class XmoFeatureBuilder:
    """Generate atom-graph and Rumer-graph fields from parsed molecule facts."""

    def __init__(self, lap_pe_k: int = 0):
        """
        Initialize the feature builder.

        Arguments:
        - lap_pe_k: Number of non-trivial Laplacian eigenvectors retained per structure graph.
        """

        self.lap_pe_k = int(lap_pe_k)

    def tensorToXyzBlock(self, atom_symbols: list[str], atom_positions: np.ndarray) -> str:
        """Convert one molecule geometry to an XYZ block for RDKit bond inference."""

        lines = [str(len(atom_symbols)), "Generated by E3VB XmoFeatureBuilder"]
        for symbol, (x, y, z) in zip(atom_symbols, atom_positions):
            lines.append(f"{symbol} {float(x):.6f} {float(y):.6f} {float(z):.6f}")
        return "\n".join(lines)

    def getBondInfo(self, atom_symbols: list[str], atom_positions: np.ndarray) -> list[tuple[str, int, str, int, str, int, int]]:
        """Infer RDKit bond orders and aromaticity from molecular geometry."""

        from rdkit.Chem import rdDetermineBonds, rdmolfiles

        xyz_block = self.tensorToXyzBlock(atom_symbols, atom_positions)
        molecule = rdmolfiles.MolFromXYZBlock(xyz_block)
        if molecule is None:
            raise ValueError("Failed to construct RDKit molecule from XYZ geometry.")

        rdDetermineBonds.DetermineBonds(molecule)
        bonds: list[tuple[str, int, str, int, str, int, int]] = []
        for bond in molecule.GetBonds():
            atom_i = bond.GetBeginAtom()
            atom_j = bond.GetEndAtom()
            idx_i = atom_i.GetIdx() + 1
            idx_j = atom_j.GetIdx() + 1
            order_name = str(bond.GetBondType())
            if order_name == "SINGLE":
                bond_order = 1
                is_aromatic = 0
            elif order_name == "DOUBLE":
                bond_order = 2
                is_aromatic = 0
            elif order_name == "TRIPLE":
                bond_order = 3
                is_aromatic = 0
            elif order_name == "AROMATIC":
                bond_order = 1
                is_aromatic = 1
            else:
                bond_order = 1
                is_aromatic = 0
            bonds.append(
                (
                    atom_i.GetSymbol(),
                    idx_i,
                    atom_j.GetSymbol(),
                    idx_j,
                    order_name,
                    bond_order,
                    is_aromatic,
                )
            )
        return bonds

    def activePairsFromStructure(self, structure_string: str, atom_from_orb: np.ndarray) -> list[tuple[int, int]]:
        """Map active occupied orbital pairs in one structure to atom-index pairs."""

        tokens = structure_string.strip().split()
        normalized_orbitals: list[int] = []
        for token in tokens:
            if ":" in token:
                continue
            if "-" in token:
                left, right = token.split("-", 1)
                normalized_orbitals.append(int(left))
                normalized_orbitals.append(int(right))
            else:
                normalized_orbitals.append(int(token))

        if len(normalized_orbitals) % 2 == 1:
            normalized_orbitals = normalized_orbitals[:-1]

        active_pairs: list[tuple[int, int]] = []
        for index in range(0, len(normalized_orbitals), 2):
            orbital_i = normalized_orbitals[index]
            orbital_j = normalized_orbitals[index + 1]
            if orbital_i == orbital_j:
                continue
            atom_i = int(atom_from_orb[orbital_i - 1, 2])
            atom_j = int(atom_from_orb[orbital_j - 1, 2])
            if atom_i == atom_j:
                continue
            active_pairs.append((atom_i, atom_j))
        return active_pairs

    def expandActiveOrbitals(self, structure_string: str) -> list[int]:
        """Expand one VB structure into its occupied active-orbital sequence."""

        occupied: list[int] = []
        for token in structure_string.strip().split():
            if ":" in token:
                continue
            if "-" in token:
                left, right = token.split("-", 1)
                occupied.append(int(left))
                occupied.append(int(right))
            else:
                occupied.append(int(token))
        return occupied

    def getInactiveOrbitalMax(self, structure_string: str) -> int | None:
        """Read the highest inactive orbital id from the leading ``1:k`` token."""

        for token in structure_string.strip().split():
            if "1:" in token:
                return int(token.split(":")[1])
        return None

    def generateX(self, parsed: ParsedXMOMolecule) -> np.ndarray:
        """Generate atom node features ``[Z, active_e, inactive_e]`` for every VB structure."""

        num_atoms = int(parsed.atom_numbers.shape[0])
        total_orbitals = int(parsed.atom_from_orb.shape[0])
        atomic_number = parsed.atom_numbers.astype(np.float32)

        inactive_orbital_max = self.getInactiveOrbitalMax(parsed.structures[0].structure_string)
        if inactive_orbital_max is None:
            inactive_orbital_max = total_orbitals - int(parsed.nao)
        active_orbital_start = inactive_orbital_max + 1

        inactive_e = np.zeros((num_atoms,), dtype=np.float32)
        if int(parsed.nae) == int(parsed.nao):
            active_orbital_count = np.zeros((num_atoms,), dtype=np.float32)
            for orbital in range(active_orbital_start, total_orbitals + 1):
                atom_id = int(parsed.atom_from_orb[orbital - 1, 2]) - 1
                active_orbital_count[atom_id] += 1.0
            inactive_e = atomic_number - active_orbital_count
        elif int(parsed.nae) > int(parsed.nao):
            best_structure_index = None
            best_weight = None
            for structure in parsed.structures:
                occupied = self.expandActiveOrbitals(structure.structure_string)
                if len(set(occupied)) != int(parsed.nao):
                    continue
                if (best_weight is None) or (structure.lowdin_weight > best_weight):
                    best_weight = structure.lowdin_weight
                    best_structure_index = structure.vb_index
            if best_structure_index is None:
                best_structure_index = int(
                    max(parsed.structures, key=lambda structure: structure.lowdin_weight).vb_index
                )
            reference_structure = next(
                structure for structure in parsed.structures if structure.vb_index == best_structure_index
            )
            reference_active_e = np.zeros((num_atoms,), dtype=np.float32)
            for orbital in self.expandActiveOrbitals(reference_structure.structure_string):
                atom_id = int(parsed.atom_from_orb[orbital - 1, 2]) - 1
                reference_active_e[atom_id] += 1.0
            inactive_e = atomic_number - reference_active_e
        else:
            raise NotImplementedError(
                f"NAE < NAO is not implemented (nae={parsed.nae}, nao={parsed.nao})."
            )

        feature_blocks: list[np.ndarray] = []
        for structure in parsed.structures:
            block = np.zeros((num_atoms, 3), dtype=np.float32)
            block[:, 0] = atomic_number
            block[:, 2] = inactive_e
            for orbital in self.expandActiveOrbitals(structure.structure_string):
                atom_id = int(parsed.atom_from_orb[orbital - 1, 2]) - 1
                block[atom_id, 1] += 1.0
            feature_blocks.append(block)
        return np.concatenate(feature_blocks, axis=1)

    def generateA(self, parsed: ParsedXMOMolecule) -> tuple[np.ndarray, list[list[int]], list[list[float]]]:
        """Generate atom adjacency and edge features following the legacy RDKit-backed rule."""

        num_structures = len(parsed.structures)
        num_atoms = int(parsed.atom_numbers.shape[0])
        adjacency_matrix = np.zeros((num_structures, num_atoms, num_atoms), dtype=np.int32)
        inactive_bond_order = np.zeros((num_atoms, num_atoms), dtype=np.int32)
        active_bond_order = np.zeros((num_structures, num_atoms, num_atoms), dtype=np.int32)
        bond_changed = np.zeros((num_atoms, num_atoms), dtype=np.int32)
        aromatic_mask = np.zeros((num_atoms, num_atoms), dtype=np.int32)

        for bond in self.getBondInfo(parsed.atom_symbols, parsed.atom_positions):
            atom_i = bond[1] - 1
            atom_j = bond[3] - 1
            bond_order = bond[5]
            is_aromatic = bond[6]
            inactive_bond_order[atom_i, atom_j] = bond_order
            inactive_bond_order[atom_j, atom_i] = bond_order
            aromatic_mask[atom_i, atom_j] = is_aromatic
            aromatic_mask[atom_j, atom_i] = is_aromatic
            adjacency_matrix[:, atom_i, atom_j] = 1
            adjacency_matrix[:, atom_j, atom_i] = 1

        has_conjugation = 0
        for structure in parsed.structures:
            active_pairs = self.activePairsFromStructure(structure.structure_string, parsed.atom_from_orb)
            for atom_i, atom_j in active_pairs:
                if inactive_bond_order[atom_i - 1, atom_j - 1] > 1:
                    has_conjugation = 1
                    break
            if has_conjugation == 1:
                break

        for structure in parsed.structures:
            structure_index = structure.vb_index
            active_pairs = self.activePairsFromStructure(structure.structure_string, parsed.atom_from_orb)
            for atom_i, atom_j in active_pairs:
                i = atom_i - 1
                j = atom_j - 1
                adjacency_matrix[structure_index, i, j] = 1
                adjacency_matrix[structure_index, j, i] = 1
                active_bond_order[structure_index, i, j] += 1
                active_bond_order[structure_index, j, i] += 1

                if aromatic_mask[i, j] == 1:
                    inactive_bond_order[i, j] = 1
                    inactive_bond_order[j, i] = 1
                    bond_changed[i, j] = 1
                    bond_changed[j, i] = 1
                if (inactive_bond_order[i, j] == 1) and (bond_changed[i, j] == 0) and (has_conjugation == 0):
                    inactive_bond_order[i, j] = 0
                    inactive_bond_order[j, i] = 0
                    bond_changed[i, j] = 1
                    bond_changed[j, i] = 1
                elif (inactive_bond_order[i, j] > 1) and (bond_changed[i, j] == 0) and (has_conjugation == 1):
                    inactive_bond_order[i, j] = 1
                    inactive_bond_order[j, i] = 1
                    bond_changed[i, j] = 1
                    bond_changed[j, i] = 1

        adjacency_list = [[], []]
        edge_features: list[list[float]] = []
        for structure_index in range(num_structures):
            for atom_i in range(num_atoms):
                for atom_j in range(num_atoms):
                    if atom_i == atom_j:
                        continue
                    if adjacency_matrix[structure_index, atom_i, atom_j] == 0:
                        continue
                    adjacency_list[0].append(atom_i + 1)
                    adjacency_list[1].append(atom_j + 1)
                    relative = parsed.atom_positions[atom_j] - parsed.atom_positions[atom_i]
                    edge_features.append(
                        [
                            float(2 * active_bond_order[structure_index, atom_i, atom_j]),
                            float(2 * inactive_bond_order[atom_i, atom_j]),
                            float(relative[0]),
                            float(relative[1]),
                            float(relative[2]),
                        ]
                    )

        return adjacency_matrix, adjacency_list, edge_features

    def buildSharedOrbitalFields(self, parsed: ParsedXMOMolecule) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Build structure-independent orbital mapping metadata."""

        num_orbitals = int(parsed.orb_role_id.shape[0])
        orbital_atom_index = np.zeros((num_orbitals, 2), dtype=np.int32)
        for orbital_id, role in enumerate(parsed.orb_role_id.tolist()):
            atoms = parsed.orb2atom[orbital_id]
            if role == 1 and len(atoms) >= 2:
                orbital_atom_index[orbital_id, 0] = int(atoms[0])
                orbital_atom_index[orbital_id, 1] = int(atoms[1])
            else:
                orbital_atom_index[orbital_id, 0] = int(atoms[0])
                orbital_atom_index[orbital_id, 1] = int(atoms[0])

        active_slot_index = np.full((num_orbitals,), -1, dtype=np.int32)
        next_slot_for_atom: dict[int, int] = {}
        for orbital_id, role in enumerate(parsed.orb_role_id.tolist()):
            if int(role) != 2:
                continue
            atom_id = int(orbital_atom_index[orbital_id, 0])
            slot = next_slot_for_atom.get(atom_id, 0)
            active_slot_index[orbital_id] = slot
            next_slot_for_atom[atom_id] = slot + 1

        return orbital_atom_index, parsed.orb_role_id.astype(np.int32), active_slot_index

    def buildRumerEdges(
        self,
        parsed: ParsedXMOMolecule,
        structure,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Build structure-specific Rumer topology from orbital roles and active pairs."""

        num_orbitals = int(parsed.orb_role_id.shape[0])
        rumer_senders: list[int] = []
        rumer_receivers: list[int] = []
        rumer_edge_type: list[int] = []

        for orbital_id in range(num_orbitals):
            role = int(parsed.orb_role_id[orbital_id])
            if role == 0:
                rumer_senders.append(orbital_id)
                rumer_receivers.append(orbital_id)
                rumer_edge_type.append(0)
            elif role == 1:
                rumer_senders.append(orbital_id)
                rumer_receivers.append(orbital_id)
                rumer_edge_type.append(1)

        for sender, receiver in structure.orb_pairs:
            rumer_senders.append(int(sender))
            rumer_receivers.append(int(receiver))
            rumer_edge_type.append(2)
            rumer_senders.append(int(receiver))
            rumer_receivers.append(int(sender))
            rumer_edge_type.append(2)

        return (
            np.asarray(rumer_senders, dtype=np.int32),
            np.asarray(rumer_receivers, dtype=np.int32),
            np.asarray(rumer_edge_type, dtype=np.int32),
        )

    def buildActiveRumerSubgraph(
        self,
        orbital_role: np.ndarray,
        structure,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
        """Build one active-only Rumer graph together with the active gather index."""

        active_orbital_index = np.flatnonzero(np.asarray(orbital_role, dtype=np.int32) == 2).astype(np.int32)
        active_local_index = {
            int(full_orbital_id): local_id
            for local_id, full_orbital_id in enumerate(active_orbital_index.tolist())
        }

        active_rumer_senders: list[int] = []
        active_rumer_receivers: list[int] = []
        active_rumer_edge_type: list[int] = []
        for sender, receiver in structure.orb_pairs:
            sender = int(sender)
            receiver = int(receiver)
            if (sender not in active_local_index) or (receiver not in active_local_index):
                continue
            active_rumer_senders.append(active_local_index[sender])
            active_rumer_receivers.append(active_local_index[receiver])
            active_rumer_edge_type.append(2)
            active_rumer_senders.append(active_local_index[receiver])
            active_rumer_receivers.append(active_local_index[sender])
            active_rumer_edge_type.append(2)

        return (
            active_orbital_index,
            np.asarray(active_rumer_senders, dtype=np.int32),
            np.asarray(active_rumer_receivers, dtype=np.int32),
            np.asarray(active_rumer_edge_type, dtype=np.int32),
        )

    def build(self, parsed: ParsedXMOMolecule) -> BuiltMoleculeSample:
        """Build all structure-level graph fields for one parsed ``.xmo`` molecule."""

        node_feature_matrix = self.generateX(parsed)
        adjacency_matrix, adjacency_list, edge_features = self.generateA(parsed)
        orbital_atom_index, orbital_role, active_slot_index = self.buildSharedOrbitalFields(parsed)
        weight_array = np.asarray([structure.lowdin_weight for structure in parsed.structures], dtype=np.float32)
        weight_max = float(np.max(weight_array))
        normalized_weight = weight_array / max(weight_max, 1e-12)

        structures: list[ProcessedStructureSample] = []
        edge_cursor = 0
        for structure in parsed.structures:
            structure_index = structure.vb_index
            num_edges = int(np.sum(adjacency_matrix[structure_index]))
            atom_node_features = node_feature_matrix[:, 3 * structure_index : 3 * (structure_index + 1)]
            atom_senders = np.asarray(
                adjacency_list[0][edge_cursor : edge_cursor + num_edges],
                dtype=np.int32,
            ) - 1
            atom_receivers = np.asarray(
                adjacency_list[1][edge_cursor : edge_cursor + num_edges],
                dtype=np.int32,
            ) - 1
            atom_pair_features = np.asarray(
                edge_features[edge_cursor : edge_cursor + num_edges],
                dtype=np.float32,
            )[:, :2]
            edge_cursor += num_edges
            lap_evals, lap_evecs = lapPeFromEdges(
                num_nodes=int(parsed.atom_numbers.shape[0]),
                senders=atom_senders,
                receivers=atom_receivers,
                k=self.lap_pe_k,
                eps=1.0e-12,
                add_self_loops=False,
            )
            rumer_senders, rumer_receivers, rumer_edge_type = self.buildRumerEdges(parsed, structure)
            (
                active_orbital_index,
                active_rumer_senders,
                active_rumer_receivers,
                active_rumer_edge_type,
            ) = self.buildActiveRumerSubgraph(orbital_role=orbital_role, structure=structure)
            structures.append(
                ProcessedStructureSample(
                    vb_index=structure_index,
                    atom_node_features=atom_node_features,
                    atom_senders=atom_senders,
                    atom_receivers=atom_receivers,
                    atom_pair_features=atom_pair_features,
                    lap_evals=lap_evals,
                    lap_evecs=lap_evecs,
                    orbital_atom_index=orbital_atom_index.copy(),
                    orbital_role=orbital_role.copy(),
                    active_slot_index=active_slot_index.copy(),
                    rumer_senders=rumer_senders,
                    rumer_receivers=rumer_receivers,
                    rumer_edge_type=rumer_edge_type,
                    active_orbital_index=active_orbital_index,
                    active_rumer_senders=active_rumer_senders,
                    active_rumer_receivers=active_rumer_receivers,
                    active_rumer_edge_type=active_rumer_edge_type,
                    target=float(normalized_weight[structure_index]),
                    target_max=weight_max,
                )
            )

        return BuiltMoleculeSample(
            molecule_id=parsed.molecule_id,
            atom_symbols=list(parsed.atom_symbols),
            atom_numbers=parsed.atom_numbers.copy(),
            atom_positions=parsed.atom_positions.copy(),
            structures=structures,
        )
